### ISSUE TITLE
Can't perform 'git push' on house-organiser' project

### ISSUE THREAD

**Issue by eranseg74** [zero-to-mastery/house-organiser#36]
Hi,
I'm trying to update the code of 'house-organiser' project.
opened a new branch and everything but whenever i try to run 'git push' I get this message:

> remote: Permission to zero-to-mastery/house-organiser.git denied to eranseg74.
> fatal: unable to access 'https://github.com/zero-to-mastery/house-organiser.git/': The requested URL returned error: 403

I added myself to the contributors list on the 'start-guidelines' project.

What am I doing wrong?

**Comment by MattCSmith** [comment]
Hi @eranseg74, 
You haven't forked the repo to your own account and therefore you are trying to write to somewhere you dont have write access. 

You will need to fork the repo, then make the changes to that fork. push to that fork and then create a pull request so that the changes between your fork and the original repo can be merged.

Hope that helps

**Comment by eranseg74** [comment]
Hey Matt,

thanx for the answer.

I thought that creating a new branch and making there all the changes is enough. according to the tutorial, when I am setting a new branch I can make all the changes there and then make the pull request in order to merge it with the master branch

**Comment by MattCSmith** [comment]
Hey, 
Forking is different from Branching. 
The following guide, should explain why branching is done. 

https://www.atlassian.com/git/tutorials/using-branches

Although it's worth noting, if you aren't the repo author or have admin rights to the repo you will need to fork before making a commit. Imagine a large company having a millions of people being able to commit all sorts of code without it being checked first. 

Forking and making a pull request, is the way to say "hey I have made a change, can it be integrated into the main code base?"

**Comment by eranseg74** [comment]
Great! Success. now the PullRequest is on the main repo. thanx, Matt! you're the man! :1st_place_medal:
